### ISSUE TITLE
Add handling of exploding dice using "!" in dice notation.

### ISSUE THREAD

**Issue by treetrnk** [treetrnk/rollem-telegram-bot#12]
For an example of this, see this article: https://en.wikipedia.org/wiki/Dice_notation#Open-ended_variations

**Comment by treetrnk** [comment]
To test this out, you will have to 
* Get telegram. Its an app for iOS and android.
* Then message @botfather. @botfather is a not that let's you create new bots. 
* Create a new bot and you will be given an authentication token
* Now that you have that, run this project and punch in the auth token as an argument like this: `./bot.py AUTH_TOKEN`

I will try my best to take a look at the PR today. Thanks for helping out!

**Comment by mattiadg** [comment]
Thank you so much!

Il 22/Ott/2016 03:00 PM, "Nathan Hare" <notifications@github.com> ha
scritto:

**Comment by treetrnk** [comment]
Closed by f7491bdb4.
