### ISSUE TITLE
Bot do not respond

### ISSUE THREAD

**Issue by GurenDLotus** [treetrnk/rollem-telegram-bot#16]
Hello guys, thanks for that amazing roller! 
But, whats happend? the bot do not respond anymore :/

**Comment by treetrnk** [comment]
Thanks for letting me know about this! I believe the issue was that Telegram recently updated their bot API. It is fixed now, but I'll leave this open for a few days just to make sure the problem has been corrected.

**Comment by GurenDLotus** [comment]
Ok, i'll keeping testing. Thank you for the response :)

**Comment by treetrnk** [comment]
It's looks to still be working on my end, so I think we're clear. Looks like it was a result of the Telegram Bot API update.
