### ISSUE TITLE
Sometimes it refuses commands on supergroups

### ISSUE THREAD

**Issue by fabiocosta0305** [treetrnk/rollem-telegram-bot#18]
When using it on supergroups, it sometimes just ignore the rolling commands, like `/roll 4df`. Adding it as a friend and use it into another conversation works correctly

**Comment by treetrnk** [comment]
I believe this may have been fixed by changing the permissions of the bot. Can you confirm @fabiocosta0305?

**Comment by treetrnk** [comment]
This issue should be fixed as of commit d39a7647, so I am closing this since I haven't gotten a response.
