### ISSUE TITLE
/help tells the user to type help(), which breaks the bot.

### ISSUE THREAD

**Issue by treetrnk** [treetrnk/rollem-telegram-bot#19]
Typing in `/help` suggests that you type in `help()`. Python then responds to this command and stalls out the bot.

**Comment by treetrnk** [comment]
Closed by commit 2c257e3.

**Comment by treetrnk** [comment]
Not actually fixed yet. The issue comes up when someone types `/r help` and then `/r help()`. Still working on a solution.

**Comment by treetrnk** [comment]
Closed by commit 283e78db

**Comment by lucascsensei** [comment]
Bot isn't working again
