### ISSUE TITLE
Bot Stopped working

### ISSUE THREAD

**Issue by Ayshir** [treetrnk/rollem-telegram-bot#27]
Hello,

Today (June, 14th), when I tried rolling some d10s, Roll'em Bot did not respond, while yesterday (June, 13th), it was working fine as always.

I have no clue on what happened or on how to solve this, if something can be done on my side.
Any help would be useful.

Thanks in advance.

**Comment by Ayshir** [comment]
A couple of hours from the halt, it resumed, like it had a huge lag issue. But now it seems to work just fine

**Comment by treetrnk** [comment]
Thanks for letting me know. I ran updates on the server yesterday and accidentally forgot to check if it was back up and running. And when it's not running, any commands sent get put in a queue that the bot has to work through once it starts up again.

Let me know if you have any other issues with it.
