### ISSUE TITLE
Permission to delete roll

### ISSUE THREAD

**Issue by coldloki** [treetrnk/rollem-telegram-bot#28]
Not really an issue, more like question. 

My D&D Telegram group is using roll bot for our in between session events. And we agreed that deleting a bad roll is forbidden. But I was wondering is it possible that admin of the group can setup that roll bot posts can’t be deleted from the thread. Or that just admin can delete them... 
Hope I’m clear enough what is the idea here?

**Comment by treetrnk** [comment]
This is actually how it already works from what I can tell. If you are the owner of a group, you can delete a message for everyone in the group. If you're not the owner, you can still delete a message, but you are only deleting it for yourself. Everyone else can still see it. Hope that helps.
