### ISSUE TITLE
help run with my token

### ISSUE THREAD

**Issue by dfyzicka** [treetrnk/rollem-telegram-bot#39]
good afternoon, I wanted to run it on my computer for tests, but I didn’t understand where to add the token for the telegram bot, at startup it swears at TOKEN = sys.argv[1], please tell me how to run it.

**Comment by treetrnk** [comment]
The token is just an argument when running the program. So if you use the command `./bot.py` to run the program, it should be `./bot.py [TOKEN_HERE]` instead, replacing `[TOKEN_HERE]` with your token.

I'll add this to the readme to make it more clear.

**Comment by dfyzicka** [comment]
Thank you very much! It was silly not to guess before that on my part))
